<?php

declare(strict_types=1);

namespace Miji\Toolbox\Modules\Security;

use Miji\Toolbox\Module;
use Miji\Toolbox\Settings\Field;
use Miji\Toolbox\Settings\Settings;
use Miji\Toolbox\Support\NotFound;
use WP;
use WP_Error;
use WP_REST_Request;

/**
 * Closes attack surface that WordPress leaves open by default.
 */
final class SecurityModule implements Module {
	/** Error codes that tell whether the username/email exists. */
	private const REVEALING_LOGIN_ERRORS = ['invalid_username', 'invalid_email', 'incorrect_password'];

	private const FILE_EDIT_CAPS = ['edit_themes', 'edit_plugins', 'edit_files'];

	public function id(): string {
		return 'security';
	}

	public function title(): string {
		return __('Security', 'wptb');
	}

	public function description(): string {
		return __('Closes doors WordPress leaves open by default. None of these affect normal visitors.', 'wptb');
	}

	public function fields(): array {
		return [
			Field::bool(
				'disable_xmlrpc',
				false,
				__('Disable XML-RPC', 'wptb'),
				__('Switches off the old XML-RPC interface (xmlrpc.php) completely: every request is answered with "forbidden".', 'wptb'),
				why: __('XML-RPC predates the REST API and is hardly used anymore, but it is a favourite target: attackers use it to try thousands of passwords in a single request and to misuse your site for attacks on others.', 'wptb'),
				sideEffects: __('Tools that still use XML-RPC stop working with this site, e.g. the Jetpack plugin and some older mobile or desktop publishing apps.', 'wptb'),
			),
			Field::bool(
				'block_user_enumeration',
				false,
				__('Hide the list of users', 'wptb'),
				__('Visitors who aren\'t logged in can no longer list the site\'s users through the REST API (/wp-json/wp/v2/users) or find login names via example.com/?author=1. Logged-in users (e.g. in the block editor) are not affected.', 'wptb'),
				why: __('Knowing the login names is half of a successful password attack. By default WordPress hands them out to anyone who asks.', 'wptb'),
				sideEffects: __('Author archives themselves still show the author\'s URL name, which equals the login name unless it was changed. To hide it completely, also remove author archives under "Blog features".', 'wptb'),
			),
			Field::bool(
				'generic_login_errors',
				false,
				__('Don\'t reveal which logins exist', 'wptb'),
				__('A failed login shows the same message whether the username or the password was wrong. "Lost your password?" shows the same confirmation whether the account exists or not.', 'wptb'),
				why: __('WordPress normally says "the username is not registered" or "the password for this user is incorrect", which confirms valid login names to attackers.', 'wptb'),
				sideEffects: __('People who mistype their username no longer get a hint that the username was the problem. If your site cannot send emails, WordPress still shows an error for existing accounts when a password reset is requested, so make sure email sending works.', 'wptb'),
			),
			Field::bool(
				'disable_application_passwords',
				false,
				__('Disable application passwords', 'wptb'),
				__('Removes application passwords (Users → Profile), which let external apps and scripts log in to the REST API with their own password.', 'wptb'),
				why: __('If nothing external connects to your site, every application password is just another way in that nobody watches.', 'wptb'),
				sideEffects: __('Integrations that use application passwords (e.g. some apps, automation tools or deployment scripts) can no longer log in.', 'wptb'),
			),
			Field::bool(
				'disable_file_editor',
				false,
				__('Disable the theme and plugin file editor', 'wptb'),
				__('Removes the code editors under Appearance → Theme File Editor and Tools → Plugin File Editor for everyone, including administrators. Installing and updating plugins and themes still works.', 'wptb'),
				why: __('Anyone who gets into an admin account could use the editor to run their own code on the server. Editing live code is also an easy way to break a site.', 'wptb'),
			),
			Field::bool(
				'security_headers',
				false,
				__('Send security headers', 'wptb'),
				__('Adds HTTP headers that tell browsers to be stricter: don\'t guess file types (X-Content-Type-Options), send only the domain as referrer to other sites (Referrer-Policy), and don\'t allow other sites to show your pages in a frame (X-Frame-Options, frame-ancestors). Also removes the X-Powered-By header that reveals the PHP version. Headers already set by your server or another plugin are kept.', 'wptb'),
				why: __('These headers protect visitors against clickjacking and some content sniffing attacks, and give other sites less information about your visitors.', 'wptb'),
				sideEffects: __('Other websites can no longer show your pages in an iframe. Only applies to pages generated by WordPress, not to files like images.', 'wptb'),
			),
		];
	}

	public function isAvailable(): bool {
		return true;
	}

	public function register(Settings $settings): void {
		$on = static fn (string $key): bool => $settings->get('security', $key) === true;

		if ($on('disable_xmlrpc')) {
			add_filter('xmlrpc_enabled', '__return_false');
			add_filter('xmlrpc_methods', '__return_empty_array', PHP_INT_MAX);
			add_filter('wp_headers', [$this, 'removePingbackHeader']);
			// the plugin boots on init 0, this runs right after
			add_action('init', [$this, 'blockXmlrpcRequest'], 1);
			// at init the XML-RPC server doesn't exist yet; its die handler would send an empty 200
			add_filter('wp_die_xmlrpc_handler', static fn (): string => '_default_wp_die_handler');
		}

		if ($on('block_user_enumeration')) {
			add_filter('rest_pre_dispatch', [$this, 'blockRestUsers'], 10, 3);
			// before redirect_canonical (10), which redirects ?author=1 to /author/<login>/
			add_action('template_redirect', [$this, 'blockAuthorQuery'], 0);
		}

		if ($on('generic_login_errors')) {
			add_filter('authenticate', [$this, 'genericLoginError'], PHP_INT_MAX);
			add_filter('shake_error_codes', [$this, 'addShakeErrorCode']);
			add_action('lostpassword_post', [$this, 'hideUnknownAccount'], 10, 2);
		}

		if ($on('disable_application_passwords')) {
			add_filter('wp_is_application_passwords_available', '__return_false');
		}

		if ($on('disable_file_editor')) {
			add_filter('map_meta_cap', [$this, 'denyFileEditing'], 10, 2);
		}

		if ($on('security_headers')) {
			add_filter('wp_headers', [$this, 'addSecurityHeaders']);
			add_action('send_headers', [$this, 'removePoweredByHeader']);
		}
	}

	public function blockXmlrpcRequest(): void {
		if (defined('XMLRPC_REQUEST') && XMLRPC_REQUEST) {
			wp_die(esc_html__('XML-RPC services are disabled on this site.', 'wptb'), '', ['response' => 403]);
		}
	}

	/**
	 * @param array<string, string> $headers
	 * @return array<string, string>
	 */
	public function removePingbackHeader(array $headers): array {
		unset($headers['X-Pingback']);
		return $headers;
	}

	/**
	 * @param mixed $result
	 * @param mixed $server
	 * @return mixed
	 */
	public function blockRestUsers(mixed $result, mixed $server, WP_REST_Request $request): mixed {
		if ($result !== null || is_user_logged_in()) {
			return $result;
		}
		$route = $request->get_route();
		if ($route === '/wp/v2/users' || str_starts_with($route, '/wp/v2/users/')) {
			return new WP_Error('rest_forbidden', __('Sorry, you are not allowed to list users.', 'wptb'), ['status' => 401]);
		}
		return $result;
	}

	/**
	 * ?author=<id> exists only to be redirected to /author/<login>/. Archives by name keep working.
	 */
	public function blockAuthorQuery(): void {
		global $wp;
		if (!$wp instanceof WP || is_user_logged_in()) {
			return;
		}
		if (isset($wp->query_vars['author']) && !isset($wp->query_vars['author_name'])) {
			NotFound::send();
		}
	}

	/**
	 * @param mixed $user WP_User, WP_Error or null
	 * @return mixed
	 */
	public function genericLoginError(mixed $user): mixed {
		if ($user instanceof WP_Error && array_intersect($user->get_error_codes(), self::REVEALING_LOGIN_ERRORS)) {
			return new WP_Error('wptb_login_failed', __('<strong>Error:</strong> The username, email address or password is incorrect.', 'wptb'));
		}
		return $user;
	}

	/**
	 * @param list<string> $codes
	 * @return list<string>
	 */
	public function addShakeErrorCode(array $codes): array {
		$codes[] = 'wptb_login_failed';
		return $codes;
	}

	/**
	 * On wp-login.php, an unknown account gets the same "check your email" page as an existing one.
	 */
	public function hideUnknownAccount(WP_Error $errors, mixed $userData): void {
		global $pagenow;
		if ($pagenow !== 'wp-login.php' || $userData) {
			return;
		}
		// other problems (empty field, captcha plugins, …) are still shown
		if (array_diff($errors->get_error_codes(), ['invalid_email'])) {
			return;
		}
		wp_safe_redirect(add_query_arg('checkemail', 'confirm', wp_login_url()));
		exit;
	}

	/**
	 * @param list<string> $caps
	 * @return list<string>
	 */
	public function denyFileEditing(array $caps, string $cap): array {
		return in_array($cap, self::FILE_EDIT_CAPS, true) ? ['do_not_allow'] : $caps;
	}

	/**
	 * @param array<string, string> $headers
	 * @return array<string, string>
	 */
	public function addSecurityHeaders(array $headers): array {
		$headers += [
			'X-Content-Type-Options' => 'nosniff',
			'Referrer-Policy' => 'strict-origin-when-cross-origin',
			'X-Frame-Options' => 'SAMEORIGIN',
		];
		if (!isset($headers['Content-Security-Policy'])) {
			$headers['Content-Security-Policy'] = "frame-ancestors 'self'";
		}
		return $headers;
	}

	public function removePoweredByHeader(): void {
		if (!headers_sent()) {
			header_remove('X-Powered-By');
		}
	}
}
